#!/bin/sh
set -eu
#set -o pipefail -o posix
#shopt -s failglob
#set -x

#if [ -x /usr/bin/authbind ]; then
#	/usr/bin/authbind --deep "$CATALINA_HOME/bin/catalina.sh" start $*
#else
#	$CATALINA_HOME/bin/catalina.sh start $*
#fi

exec gosu tomcat $CATALINA_HOME/bin/catalina.sh run >> "$CATALINA_BASE/logs/catalina.out" 2>&1
