version = 1

exclude_patterns = [
  "baseimage/image/services/sshd/keys/insecure_key"
]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "*/Dockerfile"
  ]

[[analyzers]]
name = "shell"
enabled = true
