#!/bin/sh
set -eu
(set -o | grep -q pipefail) && set -o pipefail
(set -o | grep -q posix) && set -o posix
#shopt -s failglob
#set -x

# Wait until dependencies are up and running
if [ -x /usr/local/bin/wait_for.sh ]; then
	if [ -n "${MYSQL_HOST:-}" ] && [ -n "${MYSQL_USER:-}" ] && [ -n "${MYSQL_PASSWORD:-}" ] && [ -x "$(command -v mysqladmin)" ]; then
		/usr/local/bin/wait_for.sh mysqladmin --silent --wait=9 --connect_timeout 10 -h "${MYSQL_HOST:-mysql}" -u "${MYSQL_USER:-mysql}" -p"${MYSQL_PASSWORD:-mysql}" ping
	elif [ -n "${POSTGRES_HOST:-}" ] && [ -n "${POSTGRES_USER:-}" ] && [ -n "${POSTGRES_PASSWORD:-}" ]; then
		# TODO: PGPASSWORD=${POSTGRES_PASSWORD} /usr/local/bin/wait_for.sh psql -h "${POSTGRES_HOST}" -U "${POSTGRES_USER}" -c '\q'
		# TODO: PGPASSWORD=${POSTGRES_PASSWORD} /usr/local/bin/wait_for.sh pg_isready -h "${POSTGRES_HOST}" -U "${POSTGRES_USER}"
		:
	fi
	if [ -n "${REDIS_HOST:-}" ] && [ -n "${REDIS_HOST_PORT:-6379}" ]; then
		# TODO
		:
	fi
fi
