%YAML 1.2
---
# https://docs.docker.com/compose/compose-file/
# https://hub.docker.com/explore/

version: '2.1'

services:

  pptp:
    extends:
      service: base-service
    build:
      context: vpn-pptp
      args:
      - DNS_SERVER_1=172.31.53.53
      - DNS_SERVER_2=8.8.4.4
    container_name: pptp
    ports:
    - "1723:1723"
    depends_on:
    - dnsmasq
    dns:
    - 172.31.53.53
    volumes:
    - /opt/pptp/chap-secrets:/etc/ppp/chap-secrets:ro
    - /lib/modules:/lib/modules:ro
    #- /srv/logs/pptp:/var/log
    #tmpfs:
    #- /var/log
    network_mode: host
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    cpu_shares: 128
    mem_limit: 64m
    memswap_limit: 96m
    #read_only: true
    restart: on-failure:4


########################################################################
########################################################################

#volumes:

########################################################################
########################################################################

#networks:
...
