#!/bin/sh
set -eu
(set -o | grep -q pipefail) && set -o pipefail
(set -o | grep -q posix) && set -o posix
#shopt -s failglob
#set -x

modprobe nf_conntrack_pptp
modprobe nf_nat_pptp

# enable IP forwarding
sysctl -w net.ipv4.ip_forward=1

# configure firewall
#iptables -A FORWARD -s 10.8.0.0/24 -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j TCPMSS --set-mss 1356
#or
#iptables -A FORWARD -s 10.8.0.0/24 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o eth+ -j MASQUERADE || {
	iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth+ -j MASQUERADE
}
iptables -C INPUT -p tcp --dport 1723 -j ACCEPT || {
	iptables -A INPUT -p tcp --dport 1723 -j ACCEPT
}
iptables -C FORWARD -s 10.8.0.0/24 -j ACCEPT || {
	iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
}

exec pptpd -f -C ${MAX_CONNECTIONS:-10}
