#!/bin/sh

chown -R opendkim:postfix /opt/email-relay/dkim

#exec /sbin/setuser opendkim /usr/sbin/opendkim -f -x /etc/opendkim.conf
#exec chpst -u opendkim /usr/sbin/opendkim -f -x /etc/opendkim.conf
exec /usr/sbin/opendkim -f -x /etc/opendkim.conf
