#!/bin/sh
set -eu
(set -o | grep -q pipefail) && set -o pipefail
(set -o | grep -q posix) && set -o posix
#shopt -s failglob
#set -x

#exec gosu postfix /usr/lib/postfix/sbin/master
exec /usr/lib/postfix/sbin/master
