#!/bin/sh
set -eu
#set -o pipefail -o posix
#shopt -s failglob
#set -x

if [ "$(stat -c %u /usr/local/etc/dkim)" != "$(id -u opendkim)" ] || [ "$(stat -c %g /usr/local/etc/dkim)" != "$(id -g postfix)" ]; then
	chown -R opendkim:postfix /usr/local/etc/dkim
fi

#exec gosu opendkim /usr/sbin/opendkim -f -x /etc/opendkim.conf
exec /usr/sbin/opendkim -f -x /etc/opendkim.conf
