#!/bin/sh

if [ "$(stat -c %u /opt/email-relay/dkim)" != "$(id -u opendkim)" ] || [ "$(stat -c %g /opt/email-relay/dkim)" != "$(id -g postfix)" ]; then
	chown -R opendkim:postfix /opt/email-relay/dkim
fi

#exec gosu opendkim /usr/sbin/opendkim -f -x /etc/opendkim.conf
exec /usr/sbin/opendkim -f -x /etc/opendkim.conf
