#!/bin/sh
set -eu
(set -o | grep -q pipefail) && set -o pipefail
(set -o | grep -q posix) && set -o posix
#shopt -s failglob
#set -x

# Not too late for ${WORDPRESS_*}, they haven't been cleared yet
# Wait until dependencies are up and running
if [ -x /usr/local/bin/wait_for.sh ]; then
	if [ -n "${WORDPRESS_DB_HOST:-}" ] && [ -n "${WORDPRESS_DB_USER:-}" ] && [ -n "${WORDPRESS_DB_PASSWORD:-}" ] && [ -x "$(command -v mysqladmin)" ]; then
		/usr/local/bin/wait_for.sh mysqladmin --silent --wait=9 --connect_timeout 10 -h "${WORDPRESS_DB_HOST:-mysql}" -u "${WORDPRESS_DB_USER:-wordpress}" -p"${WORDPRESS_DB_PASSWORD:-}" ping
	elif [ -n "${POSTGRES_HOST:-}" ] && [ -n "${POSTGRES_USER:-}" ] && [ -n "${POSTGRES_PASSWORD:-}" ]; then
		# TODO
		:
	fi
	if [ -n "${REDIS_HOST:-}" ] && [ -n "${REDIS_HOST_PORT:-6379}" ]; then
		# TODO
		:
	fi
fi
